// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";
import "@teyik0/furin/routes";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: never; searchInput?: never };
    "/defer-page": { search?: never; searchInput?: never };
    "/dynamic/specific": { search?: never; searchInput?: never };
    "/inline-layout": { search?: never; searchInput?: never };
    "/isr-page": { search?: never; searchInput?: never };
    "/isr-query-page": { search?: never; searchInput?: never };
    "/nested": { search?: never; searchInput?: never };
    "/nested/deep": { search?: never; searchInput?: never };
    "/query-default": { search?: { city: string }; searchInput?: { city?: string } };
    "/query-types": {
      search?: { active: boolean; filter?: { category: string }; page: number; tags?: string[] };
      searchInput?: {
        active: boolean;
        filter?: { category: string };
        page: number;
        tags?: string[];
      };
    };
    "/schema-merge-parent/child": {
      search?: { parentFilter: string; childFilter: string };
      searchInput?: { parentFilter?: string; childFilter?: string };
    };
    "/skip-layout": { search?: never; searchInput?: never };
    "/ssg-loader-page": { search?: never; searchInput?: never };
    "/ssg-page": { search?: never; searchInput?: never };
    "/ssr-page": { search?: never; searchInput?: never };
    "/suspense-page": { search?: never; searchInput?: never };
    "/sync-loader": { search?: never; searchInput?: never };
    "/sync-loader-error": { search?: never; searchInput?: never };
    "/with-loader": { search?: never; searchInput?: never };
    [key: `/dynamic-defer/${string}`]: { search?: never; searchInput?: never };
    [key: `/dynamic/${string}`]: { search?: never; searchInput?: never };
  }
}

declare module "@teyik0/furin/routes" {
  interface RouteMap {}
}
