// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/routes";

declare module "@teyik0/furin/routes" {
  interface RouteMap {
    "/": typeof import("./packages/core/tests/fixtures/pages/default/index").route;
    "/defer-page": typeof import("./packages/core/tests/fixtures/pages/default/defer-page").route;
    "/dynamic/specific": typeof import("./packages/core/tests/fixtures/pages/default/dynamic/specific").route;
    "/inline-layout": typeof import("./packages/core/tests/fixtures/pages/default/inline-layout").route;
    "/isr-page": typeof import("./packages/core/tests/fixtures/pages/default/isr-page").route;
    "/isr-query-page": typeof import("./packages/core/tests/fixtures/pages/default/isr-query-page").route;
    "/nested": typeof import("./packages/core/tests/fixtures/pages/default/nested/index").route;
    "/nested/deep": typeof import("./packages/core/tests/fixtures/pages/default/nested/deep/index").route;
    "/query-default": typeof import("./packages/core/tests/fixtures/pages/default/query-default/index").route;
    "/query-types": typeof import("./packages/core/tests/fixtures/pages/default/query-types/index").route;
    "/schema-merge-parent/child": typeof import("./packages/core/tests/fixtures/pages/default/schema-merge-parent/child/index").route;
    "/skip-layout": typeof import("./packages/core/tests/fixtures/pages/default/skip-layout").route;
    "/ssg-loader-page": typeof import("./packages/core/tests/fixtures/pages/default/ssg-loader-page").route;
    "/ssg-page": typeof import("./packages/core/tests/fixtures/pages/default/ssg-page").route;
    "/ssr-page": typeof import("./packages/core/tests/fixtures/pages/default/ssr-page").route;
    "/suspense-page": typeof import("./packages/core/tests/fixtures/pages/default/suspense-page").route;
    "/sync-loader": typeof import("./packages/core/tests/fixtures/pages/default/sync-loader").route;
    "/sync-loader-error": typeof import("./packages/core/tests/fixtures/pages/default/sync-loader-error").route;
    "/with-loader": typeof import("./packages/core/tests/fixtures/pages/default/with-loader/index").route;
    [
      key: `/dynamic-defer/${string}`
    ]: typeof import("./packages/core/tests/fixtures/pages/default/dynamic-defer/[slug]/index").route;
    [
      key: `/dynamic/${string}`
    ]: typeof import("./packages/core/tests/fixtures/pages/default/dynamic/[id]/index").route;
  }
}
