// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";
import "@teyik0/furin/search";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: { city: string } };
  }
}

declare module "@teyik0/furin/search" {
  interface RouteManifest {
    "/": { search?: { city: string } };
  }
}
