// Auto-generated by Furin. Do not edit manually.
/// <reference types="@teyik0/furin/env" />
import "@teyik0/furin/link";

declare module "@teyik0/furin/link" {
  interface RouteManifest {
    "/": { search?: never; searchInput?: never };
    "/docs": { search?: never; searchInput?: never };
    "/docs/api-routes": { search?: never; searchInput?: never };
    "/docs/caching": { search?: never; searchInput?: never };
    "/docs/cli": { search?: never; searchInput?: never };
    "/docs/comparison": { search?: never; searchInput?: never };
    "/docs/configuration": { search?: never; searchInput?: never };
    "/docs/data-loading": { search?: never; searchInput?: never };
    "/docs/defer": { search?: never; searchInput?: never };
    "/docs/deployment": { search?: never; searchInput?: never };
    "/docs/dev-hmr": { search?: never; searchInput?: never };
    "/docs/error-handling": { search?: never; searchInput?: never };
    "/docs/getting-started": { search?: never; searchInput?: never };
    "/docs/head-seo": { search?: never; searchInput?: never };
    "/docs/layouts": { search?: never; searchInput?: never };
    "/docs/link-navigation": { search?: never; searchInput?: never };
    "/docs/logging": { search?: never; searchInput?: never };
    "/docs/plugins": { search?: never; searchInput?: never };
    "/docs/rendering": { search?: never; searchInput?: never };
    "/docs/routing": { search?: never; searchInput?: never };
  }
}
