import { rmSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import type { BunTargetApp } from "../adapter/bun.ts";
import { buildClient } from "../build/client.ts";
import { buildEntrySource } from "../build/entry-template.ts";
import { ensureDir, toPosixPath } from "../build/shared.ts";
import { buildSSGCacheSnapshot } from "../build/ssg-cache.ts";
import type { BuildAppOptions, PackageTargetBuildManifest } from "../build/types.ts";
import { ssgRouteCache } from "../server/cache/ssg.ts";
import { generateProdIndexHtml } from "../server/render/shell.ts";
import { setProductionTemplateContent } from "../server/render/template.ts";

/**
 * `--target package` — builds a furin app as a PUBLISHABLE Elysia plugin
 * instead of a bootable server. Output (`.furin/build/package/`):
 *
 * - `client/`      content-hashed chunks + index.html SSR template
 * - `register.js`  side-effect module registering the app's CompileContext;
 *                  page modules are bundled in, but everything from
 *                  node_modules (incl. @teyik0/furin itself) stays external so
 *                  the host and the register module share ONE furin runtime
 * - `index.js`     `createFurinApp()` factory the host `.use()`es
 * - `index.d.ts`   minimal typings for the factory
 *
 * The host composes it like any Elysia plugin:
 *
 * ```ts
 * import { createFurinApp as admin } from "@org/admin/furin";
 * new Elysia().use(await furin({...})).use(await admin()).listen(3000)
 * ```
 *
 * In a monorepo the baked relative `pagesDir` still points at real sources,
 * so the same factory works under `bun --hot` (dev scans live). A published
 * package without sources is production-only; its context is found by prefix.
 */
export async function buildPackageTarget(
  app: BunTargetApp,
  rootDir: string,
  buildRoot: string,
  options: BuildAppOptions
): Promise<PackageTargetBuildManifest> {
  const { prefix, root, routes, pagesDir } = app;
  const targetDir = join(buildRoot, "package");

  rmSync(targetDir, { force: true, recursive: true });
  ensureDir(targetDir);

  const { entryChunk, cssChunks } = await buildClient(routes, {
    outDir: targetDir,
    rootLayout: root.path,
    plugins: options.plugins,
    publicPath: `${prefix}/_client/`,
    basePath: prefix,
    clientLogging: options.clientLogging ?? false,
  });

  const buildId = Bun.hash(`${prefix}\n${entryChunk}\n${cssChunks.join("\n")}`)
    .toString(16)
    .slice(0, 12);

  const clientDir = join(targetDir, "client");
  const indexHtml = generateProdIndexHtml(entryChunk, cssChunks, buildId, undefined, false);
  writeFileSync(join(clientDir, "index.html"), indexHtml);

  // SSG snapshot renders through the build-time default state bucket.
  setProductionTemplateContent(indexHtml);
  ssgRouteCache().clear();
  const ssgCache = await buildSSGCacheSnapshot(routes, root, "http://localhost");

  const rootConventions =
    root.errorPath || root.notFoundPath
      ? {
          errorPath: root.errorPath ? toPosixPath(root.errorPath) : undefined,
          notFoundPath: root.notFoundPath ? toPosixPath(root.notFoundPath) : undefined,
        }
      : undefined;
  const routeMetadata: Record<
    string,
    {
      segmentBoundaries: Array<{
        depth: number;
        path: string;
        errorPath?: string;
        notFoundPath?: string;
      }>;
    }
  > = {};
  for (const route of routes) {
    routeMetadata[toPosixPath(route.path)] = {
      segmentBoundaries: route.segmentBoundaries.map((b) => ({
        depth: b.depth,
        path: toPosixPath(b.path),
        errorPath: b.errorPath ? toPosixPath(b.errorPath) : undefined,
        notFoundPath: b.notFoundPath ? toPosixPath(b.notFoundPath) : undefined,
      })),
    };
  }

  // 1. register.ts — context registration side-effect module.
  const registerSource = buildEntrySource({
    apps: [
      {
        buildId,
        prefix,
        rootPath: root.path,
        routes: routes.map((r) => ({ pattern: r.pattern, path: r.path, mode: r.mode })),
        rootConventions,
        routeMetadata,
        ssgCache,
      },
    ],
    headerComment: "// Auto-generated by `furin build --target package` — do not edit",
    mode: "register",
  });
  const registerEntry = join(targetDir, "register.ts");
  writeFileSync(registerEntry, registerSource);

  const result = await Bun.build({
    entrypoints: [registerEntry],
    outdir: targetDir,
    target: "bun",
    // Keep EVERY dependency external (incl. @teyik0/furin): the host must
    // share one copy of the furin runtime with this register module — only
    // the package's own page sources get bundled in.
    packages: "external",
    naming: { entry: "[name].[ext]", chunk: "[name]-[hash].[ext]" },
    sourcemap: "none",
    minify: false,
    plugins: options.plugins,
  });
  if (!result.success) {
    throw new AggregateError(result.logs, "[furin] package register build failed");
  }
  rmSync(registerEntry, { force: true });
  rmSync(join(targetDir, "_hydrate.tsx"), { force: true });

  // 2. index.js — the factory the host mounts. The baked relative pagesDir
  // keeps monorepo dev working; in a published package the compile context is
  // resolved by prefix instead.
  const relativePagesDir = toPosixPath(relative(targetDir, resolve(rootDir, pagesDir)));
  const factorySource = `// Auto-generated by \`furin build --target package\` — do not edit
import { fileURLToPath } from "node:url";
import { furin } from "@teyik0/furin";
import "./register.js";

const PAGES_DIR = fileURLToPath(new URL(${JSON.stringify(`./${relativePagesDir}`)}, import.meta.url));
const CLIENT_DIR = fileURLToPath(new URL("./client", import.meta.url));

/**
 * Mounts this packaged furin app as an Elysia plugin.
 *
 * @param {object} [options] Extra furin() options (logger, sync, ...).
 * @returns {Promise<import("elysia").Elysia>}
 */
export function createFurinApp(options = {}) {
  return furin({
    pagesDir: PAGES_DIR,
    prefix: ${JSON.stringify(prefix)},
    clientDir: CLIENT_DIR,
    ...options,
  });
}

export const prefix = ${JSON.stringify(prefix)};
`;
  writeFileSync(join(targetDir, "index.js"), factorySource);

  const dtsSource = `import type { Elysia } from "elysia";

/** Mounts this packaged furin app as an Elysia plugin. */
export declare function createFurinApp(options?: Record<string, unknown>): Promise<Elysia>;
export declare const prefix: string;
`;
  writeFileSync(join(targetDir, "index.d.ts"), dtsSource);

  console.log(`[furin] Package artifact: ${toPosixPath(relative(rootDir, targetDir))}`);

  return {
    buildId,
    generatedAt: new Date().toISOString(),
    prefix,
    targetDir: toPosixPath(relative(rootDir, targetDir)),
  };
}
