import { expect, mock, test } from "bun:test";
import {
  installDom,
  resetDomState,
  useDomTests as setupDomTests,
} from "../../../packages/core/tests/helpers/dom.ts";

installDom();
resetDomState();

const { act, createElement } = await import("react");
const { createRoot } = await import("react-dom/client");

setupDomTests();

const createCalls: unknown[][] = [];

mock.module("../src/lib/api", () => ({
  apiClient: {
    api: {
      boards: {
        post: (...args: unknown[]) => {
          createCalls.push(args);
          return Promise.resolve({ data: { id: "board-created" }, error: null });
        },
      },
    },
  },
}));

const { CreateBoardForm } = await import("../src/components/create-board-form");

function setInputValue(element: HTMLInputElement, value: string): void {
  const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(element), "value")?.set;
  setter?.call(element, value);
  const EventConstructor = document.defaultView?.Event ?? Event;
  element.dispatchEvent(new EventConstructor("input", { bubbles: true }));
  element.dispatchEvent(new EventConstructor("change", { bubbles: true }));
}

test("creates a board with the idempotency key generated by useSync", async () => {
  const container = document.createElement("div");
  const root = createRoot(container);
  document.body.appendChild(container);

  try {
    await act(() => root.render(createElement(CreateBoardForm)));
    const input = container.querySelector<HTMLInputElement>('input[aria-label="New board name"]');
    const form = input?.closest("form");
    expect(input).not.toBeNull();
    expect(form).not.toBeNull();

    await act(() => {
      if (input) {
        setInputValue(input, "Project Beta");
      }
    });
    await act(async () => {
      form?.querySelector<HTMLButtonElement>('button[type="submit"]')?.click();
      await Promise.resolve();
    });

    expect(createCalls).toHaveLength(1);
    expect(createCalls[0]?.[0]).toEqual({ name: "Project Beta" });
    expect(createCalls[0]?.[1]).toEqual({
      headers: { "Idempotency-Key": expect.any(String) },
    });
    expect(input?.value).toBe("");
  } finally {
    await act(() => root.unmount());
    container.remove();
  }
});
